#vi deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
 name: web-proj-268
 labels:
   app: nginx
spec:
 replicas: 1
 selector:
   matchLabels:
     app: nginx
 template:
   metadata:
     labels:
       app: nginx
   spec:
     containers:
     - name: nginx
       image: nginx:1.16
       ports:
       - containerPort: 80

# kubectl apply -f deployment.yaml

#kubectl get deployments

#kubectl get pods

#vi deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
 name: web-proj-268
 labels:
   app: nginx
spec:
 replicas: 1
 selector:
   matchLabels:
     app: nginx
 template:
   metadata:
     labels:
       app: nginx
   spec:
     containers:
     - name: nginx
       image: nginx:1.17
       ports:
       - containerPort: 80

# kubectl apply -f deployment.yaml --record

#kubectl get deployments

#kubectl get pods

#kubectl apply -f deployment.yaml